"""
NFL APP Health Monitor email transport.

Delivery-only component:
- Uses the host's existing sendmail binary.
- Does not observe health.
- Does not modify incident state.
- Does not execute repairs.
- Does not modify scheduling.
"""

from __future__ import annotations

import subprocess
from email.message import EmailMessage
from typing import Any, Iterable


SENDMAIL_PATH = "/usr/sbin/sendmail"

DEFAULT_RECIPIENTS = (
    "Mwynn229@gmail.com",
    "Mwynnjr@comcast.net",
)

DEFAULT_FROM = "nfl-health-monitor@localhost"


class EmailDeliveryError(RuntimeError):
    pass


def _clean(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def format_subject(message: dict[str, Any]) -> str:
    event_type = _clean(message.get("event_type")) or "HEALTH_EVENT"
    severity = (
        _clean(message.get("severity"))
        or _clean(message.get("status"))
        or "NOTICE"
    )
    return f"[NFL APP] {severity}: {event_type}"


def format_body(message: dict[str, Any]) -> str:
    preferred = (
        "event_type",
        "severity",
        "status",
        "incident_id",
        "check_id",
        "scope",
        "reason_code",
        "repair_id",
        "created_at_utc",
    )

    lines = ["NFL APP Health Monitor", ""]

    emitted = set()

    for key in preferred:
        if key in message:
            lines.append(f"{key}: {_clean(message.get(key))}")
            emitted.add(key)

    # Preserve additional non-secret event context.
    for key in sorted(message):
        if key in emitted:
            continue
        if key in {
            "delivery_state",
            "delivery_attempts",
            "last_delivery_attempt_utc",
            "last_delivery_error_type",
        }:
            continue

        value = message.get(key)

        if isinstance(value, (str, int, float, bool)) or value is None:
            lines.append(f"{key}: {_clean(value)}")

    lines.extend(
        [
            "",
            "Generated by NFL APP Health Monitor.",
        ]
    )

    return "\n".join(lines)


def send_email(
    message: dict[str, Any],
    *,
    recipients: Iterable[str] = DEFAULT_RECIPIENTS,
    sender: str = DEFAULT_FROM,
    sendmail_path: str = SENDMAIL_PATH,
) -> None:
    recipients = tuple(
        address.strip()
        for address in recipients
        if address and address.strip()
    )

    if not recipients:
        raise EmailDeliveryError("NO_EMAIL_RECIPIENTS")

    email = EmailMessage()
    email["From"] = sender
    email["To"] = ", ".join(recipients)
    email["Subject"] = format_subject(message)
    email.set_content(format_body(message))

    try:
        proc = subprocess.run(
            [sendmail_path, "-t", "-oi"],
            input=email.as_bytes(),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=15,
        )
    except Exception as exc:
        raise EmailDeliveryError(
            f"SENDMAIL_EXECUTION_FAILED:{type(exc).__name__}"
        ) from exc

    if proc.returncode != 0:
        raise EmailDeliveryError(
            f"SENDMAIL_RC_{proc.returncode}:"
            f"{proc.stderr.decode(errors='replace').strip()}"
        )


def sender(message: dict[str, Any]) -> None:
    """Adapter compatible with health_monitor.outbox.deliver_pending()."""
    send_email(message)
